question_data = [
    {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
                                      "question": "In aeronautics, flaps and slats are used to control what on an aircraft?",
                                      "correct_answer": "Lift", "incorrect_answers": ["Thrust", "Drag", "Weight "]},
                                     {"category": "Geography", "type": "multiple", "difficulty": "medium",
                                      "question": "What is the largest non-continental island in the world?",
                                      "correct_answer": "Greenland",
                                      "incorrect_answers": ["New Guinea", "Borneo", "Madagascar"]},
                                     {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
                                      "question": "What does AD stand for in relation to Windows Operating Systems? ",
                                      "correct_answer": "Active Directory",
                                      "incorrect_answers": ["Alternative Drive", "Automated Database",
                                                            "Active Department"]},
                                     {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
                                      "question": "This movie contains the quote, &quot;What we&#039;ve got here is a failure to communicate.&quot;",
                                      "correct_answer": "Cool Hand Luke",
                                      "incorrect_answers": ["Bonnie and Clyde", "The Graduate",
                                                            "In the Heat of the Night"]},
                                     {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
                                      "question": "What was the nickname given to the Hughes H-4 Hercules, a heavy transport flying boat which achieved flight in 1947?",
                                      "correct_answer": "Spruce Goose",
                                      "incorrect_answers": ["Noah&#039;s Ark", "Fat Man", "Trojan Horse"]},
                                     {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
                                      "difficulty": "medium",
                                      "question": "The main protagonist of the fourth part of JoJo&#039;s Bizarre Adventure is which of the following?",
                                      "correct_answer": "Josuke Higashikata",
                                      "incorrect_answers": ["Yoshikage kira", "Koichi Hirose", "Joey JoJo"]},
                                     {"category": "History", "type": "multiple", "difficulty": "medium",
                                      "question": "Joseph Stalin had a criminal past doing what?",
                                      "correct_answer": "Robbing Trains",
                                      "incorrect_answers": ["Murder for Hire", "Tax Evasion", "Identity Fraud"]},
                                     {"category": "Entertainment: Music", "type": "multiple", "difficulty": "hard",
                                      "question": "Electronic artists Boys Noize and Skrillex have collaborated and released tracks under what name?",
                                      "correct_answer": "Dog Blood",
                                      "incorrect_answers": ["Jack &Uuml;", "What So Not", "Noisia"]},
                                     {"category": "Celebrities", "type": "multiple", "difficulty": "hard",
                                      "question": "Billy Herrington is from which US state?",
                                      "correct_answer": "New York",
                                      "incorrect_answers": ["Arizona", "California", "Georgia"]},
                                     {"category": "Entertainment: Cartoon & Animations", "type": "multiple",
                                      "difficulty": "medium",
                                      "question": "What ability does Princess Sofia the First have from her amulet that allows her to breathe underwater?",
                                      "correct_answer": "Mermaid Transformation",
                                      "incorrect_answers": ["Artificial Gills", "Bubble Head", "Bubble Shield"]}]

